name: feast_mobile_email
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mailer: ^6.1.0
  otp: ^3.1.4
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  pin_code_fields: ^8.0.1
  easy_image_viewer: ^1.5.0
  go_router: ^14.1.4
  provider: ^6.1.2
  geolocator: ^12.0.0

dev_dependencies:

flutter:
  uses-material-design: true

  assets: 
    - assets/png/
    - assets/svg/